// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wumpus.Database;

#nullable disable

namespace Wumpus.Database.Migrations
{
    [DbContext(typeof(WumpusDbContext))]
    [Migration("20251111065729_AddNotificationFramework")]
    partial class AddNotificationFramework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wumpus.Shared.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntil")
                        .HasFilter("\"LockedUntil\" IS NOT NULL");

                    b.HasIndex("ReportId");

                    b.HasIndex("SubscriberId", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Reports", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeartbeatTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeat");

                    b.ToTable("Subscribers", (string)null);
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Error", b =>
                {
                    b.HasBaseType("Wumpus.Shared.Models.Report");

                    b.ToTable("Errors", (string)null);
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Event", b =>
                {
                    b.HasBaseType("Wumpus.Shared.Models.Report");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Notification", b =>
                {
                    b.HasOne("Wumpus.Shared.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wumpus.Shared.Models.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Report", b =>
                {
                    b.OwnsOne("Wumpus.Shared.Models.StandardPayload", "Standard", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ComputerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Environment")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GameVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("SequenceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("ReportId");

                            b1.HasIndex("ComputerId");

                            b1.HasIndex("Environment");

                            b1.HasIndex("GameId");

                            b1.HasIndex("GameVersion");

                            b1.HasIndex("Platform");

                            b1.HasIndex("UserId");

                            b1.ToTable("Reports");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("Standard")
                        .IsRequired();
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Error", b =>
                {
                    b.HasOne("Wumpus.Shared.Models.Report", null)
                        .WithOne()
                        .HasForeignKey("Wumpus.Shared.Models.Error", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wumpus.Shared.Models.ErrorPayload", "Data", b1 =>
                        {
                            b1.Property<Guid>("ErrorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Log")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("StackTrace")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ErrorId");

                            b1.HasIndex("Severity");

                            b1.ToTable("Errors");

                            b1.WithOwner()
                                .HasForeignKey("ErrorId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Wumpus.Shared.Models.Event", b =>
                {
                    b.HasOne("Wumpus.Shared.Models.Report", null)
                        .WithOne()
                        .HasForeignKey("Wumpus.Shared.Models.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wumpus.Shared.Models.EventPayload", "Data", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Dictionary<string, object>>("Metadata")
                                .HasColumnType("jsonb");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("UserId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("EventId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
