// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Domovoy.Database;

#nullable disable

namespace Domovoy.Database.Migrations
{
    [DbContext(typeof(DomovoyDbContext))]
    [Migration("20251110092205_SwitchToTPT")]
    partial class SwitchToTPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domovoy.Shared.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("Platform");

                    b.HasIndex("Timestamp");

                    b.ToTable("Reports", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domovoy.Shared.Models.Error", b =>
                {
                    b.HasBaseType("Domovoy.Shared.Models.Report");

                    b.ToTable("Errors", (string)null);
                });

            modelBuilder.Entity("Domovoy.Shared.Models.Event", b =>
                {
                    b.HasBaseType("Domovoy.Shared.Models.Report");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Domovoy.Shared.Models.Error", b =>
                {
                    b.HasOne("Domovoy.Shared.Models.Report", null)
                        .WithOne()
                        .HasForeignKey("Domovoy.Shared.Models.Error", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domovoy.Shared.Models.ErrorPayload", "Data", b1 =>
                        {
                            b1.Property<Guid>("ErrorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Context")
                                .HasColumnType("text");

                            b1.Property<string>("ExceptionType")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("StackTrace")
                                .HasColumnType("text");

                            b1.HasKey("ErrorId");

                            b1.HasIndex("Severity");

                            b1.ToTable("Errors");

                            b1.WithOwner()
                                .HasForeignKey("ErrorId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Domovoy.Shared.Models.Event", b =>
                {
                    b.HasOne("Domovoy.Shared.Models.Report", null)
                        .WithOne()
                        .HasForeignKey("Domovoy.Shared.Models.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domovoy.Shared.Models.EventPayload", "Data", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Dictionary<string, object>>("Metadata")
                                .HasColumnType("jsonb");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("UserId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("EventId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
