// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Domovoy.Database;

#nullable disable

namespace Domovoy.Database.Migrations
{
    [DbContext(typeof(DomovoyDbContext))]
    [Migration("20251110061400_RemoveUnusedFields")]
    partial class RemoveUnusedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domovoy.Shared.Models.CrashReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("StackTraceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StackTraceHash");

                    b.HasIndex("Timestamp");

                    b.ToTable("CrashReports");
                });

            modelBuilder.Entity("Domovoy.Shared.Models.CrashReport", b =>
                {
                    b.OwnsOne("Domovoy.Shared.Models.CrashReportCore", "Core", b1 =>
                        {
                            b1.Property<Guid>("CrashReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExceptionMessage")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("ExceptionType")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("GameVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("StackTrace")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CrashReportId");

                            b1.HasIndex("GameVersion");

                            b1.HasIndex("Platform");

                            b1.ToTable("CrashReports");

                            b1.WithOwner()
                                .HasForeignKey("CrashReportId");
                        });

                    b.Navigation("Core")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
